### GET Home

GET http://localhost:3000 HTTP/1.1

### GET User

GET http://localhost:3000/users HTTP/1.1

### POST User

POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "name": "Luis",
  "surname": "Luisito",
  "email": "luis@luisito.com"
}

### GET Secure

GET http://localhost:3000/secure?key=1234567&hash=890 HTTP/1.1

### POST Secure

POST http://localhost:3000/secure HTTP/1.1
content-type: application/json

{
  "hello": "world"
}

### PUT Secure

PUT http://localhost:3000/secure HTTP/1.1
content-type: application/json

{
  "hello": "world"
}

### DELETE Secure

DELETE http://localhost:3000/secure HTTP/1.1
content-type: application/json

{
  "hello": "world"
}
