name: test
run-name: Testing Sirocco server
on: [push]
jobs:
  testing_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install conan
      - run: conan profile detect
      - run: apt install libfmt-dev
      - run: make init
      - run: make sirocco
      - run: make test
